export const LOAD_FEED = "LOAD_FEED";
export const RESET_FEED = "RESET_FEED";

export const SET_SELECTED_OBJECT = "SET_SELECTED_OBJECT";
export const RESET_SELECTED_OBJECT = "RESET_SELECTED_OBJECT";

export const SET_PAGE = "SET_PAGE";
export const RESET_PAGE = "RESET_PAGE";

export const SET_QUERY = "SET_QUERY";
export const RESET_QUERY = "RESET_QUERY";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const RESTORE_USER = "RESTORE_USER";

export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_MODAL_WITH_DATA = "TOGGLE_MODAL_WITH_DATA";

export const CREATE_DOCUMENT = "CREATE_DOCUMENT";
export const UPDATE_DOCUMENT = "CREATE_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";

export const SET_DESTINATION = "CREATE_DESTINATION";
